# Then: podman compose -f docker-compose.yml up --build -d
services:
  app:
    container_name: laravel-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.env:/app/.env:ro
    ports:
      - '8080:8080'
    restart: always
